all: trab1
trab1: config.cpp tinyxml.cpp tinystr.cpp tinyxmlerror.cpp tinyxmlparser.cpp graphics.cpp main.cpp
	g++ config.cpp tinyxml.cpp tinystr.cpp tinyxmlerror.cpp tinyxmlparser.cpp graphics.cpp main.cpp -o config -lglut -lGLU -lGL
clean: rm -rf *.o
