all: trab
trab: config.cpp tinyxml.cpp tinystr.cpp tinyxmlerror.cpp tinyxmlparser.cpp graphics.cpp main.cpp
	g++ config.cpp tinyxml.cpp tinystr.cpp tinyxmlerror.cpp tinyxmlparser.cpp graphics.cpp main.cpp -o trabalhocg -lglut -lGLU -lGL
clean: 
	rm -rf trabalhocg *.o
